import { StudioPhoto, UserProfile } from './types';

export const INITIAL_USER: UserProfile = {
  name: 'Maya',
  email: 'contacto@maboutique.com',
  storeName: 'Boutique Reseller Pro',
  tier: 'Plan Inicial para Revendedores',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBfu84bd7LUtwYSK4yh3Nu2AnH0s6QpLGpHwIALHTdEoWO7kgBx7ULrHEhXoNxXJDarW13Qaspvvn95V2F3zPipioyhC97wLqy6vh9Rf5_lunduvnz1Tz2x-klf8eAQOcmv_Ftn04tzd4YHnm_Mlwf6woKUUjdengjDihPVzYwnuwgBUCz1DjyhIv-e7Y1fGt4CevZXyy8WmXlydwCVrwT-MHEV2ruuTiY6giSHmV2YfxiQeV8GUyFF',
  usedCredits: 15,
  totalCredits: 50,
  renewsInDays: 18,
};

export const LOGO_URL = 'https://lh3.googleusercontent.com/aida/AEtjO1Vd6UdffjnUqL24abRnPFzceCOBa0F8sF8Jof1SxFt0x8oQ9tfe9kjExEvXiyfDzR-4LbTmXqe5q90trIik8wBxc2vEnJ8JmxWYRvelTOJwB3xcOB_R0TdakxxEoGor_b45kRB3AgxmEjr24fUzSLUXSmwjBJ-VSf2twY-lycNQqh62vJNSRkMzi4q4HM68ZOnhEFl_umcTMW_oRjc103DmjLcsE5gSW-ZzkYkyL_TvofrN4xi-9nbqDUk';

export const INITIAL_PHOTOS: StudioPhoto[] = [
  {
    id: 'photo-1',
    filename: 'mocasines_gucci_vintage.jpg',
    dimensions: '3024 × 4032 px',
    filesize: '4.2 MB',
    status: 'edited',
    badgeText: 'Editada • Sin fondo',
    badgeType: 'emerald',
    timeAgo: 'Hace 2 min',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCewuifRjsn9ftiy8EHTp0b45yaEAsA_4lQWUOmuRX9cBnKs-mcoW_To5L6JGi9hDrkeeVVPXTUGjcXkYLJwIOk8AfCy6OojUU5QmlBraILUducFe2UsLsZp_fxHclydg15E1GXJ2_mbiCuLS61zFCCjVWT5PmJ60BfVLgZCH6vxj4CTLVDzTie-_2RvPNTDxDr2-fSK2o5Ymk2ZJ8m2yNTzExtTx0xGAoG5_9efSQa1zhzaRbvaSPo',
    rawImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCewuifRjsn9ftiy8EHTp0b45yaEAsA_4lQWUOmuRX9cBnKs-mcoW_To5L6JGi9hDrkeeVVPXTUGjcXkYLJwIOk8AfCy6OojUU5QmlBraILUducFe2UsLsZp_fxHclydg15E1GXJ2_mbiCuLS61zFCCjVWT5PmJ60BfVLgZCH6vxj4CTLVDzTie-_2RvPNTDxDr2-fSK2o5Ymk2ZJ8m2yNTzExtTx0xGAoG5_9efSQa1zhzaRbvaSPo',
    isolatedImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA-jSY10S5qFAy5IJ6q5pjtocFEHhbGgcOb4KPXvo7wQut5nqr5FXgjjc1NBhasojoDtiOHB0dAkgqZXxJ2hZscaFGVHZbC9WWSibmg7CKdNgD9qAlmmd8gQNjG8Cp3NTSLRyQKfbpDr_EBr5KceHzKx_h3xq-dmHut5x5P0GL8yaBERMhmvyIioW7BHqjZF2RzuoG5WEQJVf7qxmg6f-vvVqS_HdwfT_8kPjHPpOtAnZ1LlxYdPtUk',
    altText: 'Mocasines vintage de cuero caoba con herraje sobre fondo de estudio impecable',
    presetApplied: 'Blanco Puro',
    contrast: 18,
    saturation: 10,
    brightness: 5,
    isBgRemoved: true,
    selectedBackdrop: 'white',
    isLightingImproved: true,
    platformPreset: '1200 × 1600 px',
    exportFormat: 'jpg',
    exportQuality: 100,
  },
  {
    id: 'photo-2',
    filename: 'blazer_lino_verano.png',
    dimensions: '2800 × 3500 px',
    filesize: '3.8 MB',
    status: 'in_progress',
    badgeText: 'En proceso',
    badgeType: 'amber',
    timeAgo: 'Hace 14 min',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQBMJr25FLEfyIrm-Tm7AngBTssGog19ki0njBf_W7Phgf4QXxDklgr3U598FNN9eFAkvuf2LCb3g0kZron6QJ3j8Mzok4_7HhXmSeRwxZxKf8qEiOB_z2M5hSl7gQfqXHWGXCHxnVljWnk1ebzm_xUVleg-BJqYBj0dYlIAw5efGCCF_c9SedGqpfRJTejkOGqkASJ_rBNVfuNscCHZtJ-JvhicdWevIMpSR8zKdywC3FTbiB_7OG',
    rawImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQBMJr25FLEfyIrm-Tm7AngBTssGog19ki0njBf_W7Phgf4QXxDklgr3U598FNN9eFAkvuf2LCb3g0kZron6QJ3j8Mzok4_7HhXmSeRwxZxKf8qEiOB_z2M5hSl7gQfqXHWGXCHxnVljWnk1ebzm_xUVleg-BJqYBj0dYlIAw5efGCCF_c9SedGqpfRJTejkOGqkASJ_rBNVfuNscCHZtJ-JvhicdWevIMpSR8zKdywC3FTbiB_7OG',
    isolatedImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQBMJr25FLEfyIrm-Tm7AngBTssGog19ki0njBf_W7Phgf4QXxDklgr3U598FNN9eFAkvuf2LCb3g0kZron6QJ3j8Mzok4_7HhXmSeRwxZxKf8qEiOB_z2M5hSl7gQfqXHWGXCHxnVljWnk1ebzm_xUVleg-BJqYBj0dYlIAw5efGCCF_c9SedGqpfRJTejkOGqkASJ_rBNVfuNscCHZtJ-JvhicdWevIMpSR8zKdywC3FTbiB_7OG',
    altText: 'Blazer de verano de lino sastrero en tono avena con caída relajada',
    presetApplied: 'Cálido Lifestyle',
    contrast: 8,
    saturation: 22,
    brightness: 4,
    isBgRemoved: false,
    selectedBackdrop: 'neutral',
    isLightingImproved: true,
    platformPreset: '1200 × 1600 px',
    exportFormat: 'jpg',
    exportQuality: 95,
  },
  {
    id: 'photo-3',
    filename: 'cartera_tote_cuero_caramelo.jpg',
    dimensions: '2560 × 3200 px',
    filesize: '3.1 MB',
    status: 'edited',
    badgeText: 'Editada • Luz de estudio',
    badgeType: 'emerald',
    timeAgo: 'Hace 1 h',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA79zvvAcTRSkqVDVwugT0zuVG6ROkk_f7_b1AJBmVzya325ocTY9eY1OmhEypYfHTVVueC1JiRKve9TT0AY5ga6eDIPRCR5N6sbRMp-Gg3v7DS7-aP-iAD4dpSEtfPEI6qiDgsKoStZxsQXbsjIQ08K0io-zA_iMoYJo-g3aQBrmp861EG62MbzT_tw_9H9vkeKN33rIWj9cXUGe7ljyAC9_EiE78-jpZ3UpSBdFJjrGe5RdV_2KXz',
    rawImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA79zvvAcTRSkqVDVwugT0zuVG6ROkk_f7_b1AJBmVzya325ocTY9eY1OmhEypYfHTVVueC1JiRKve9TT0AY5ga6eDIPRCR5N6sbRMp-Gg3v7DS7-aP-iAD4dpSEtfPEI6qiDgsKoStZxsQXbsjIQ08K0io-zA_iMoYJo-g3aQBrmp861EG62MbzT_tw_9H9vkeKN33rIWj9cXUGe7ljyAC9_EiE78-jpZ3UpSBdFJjrGe5RdV_2KXz',
    isolatedImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA79zvvAcTRSkqVDVwugT0zuVG6ROkk_f7_b1AJBmVzya325ocTY9eY1OmhEypYfHTVVueC1JiRKve9TT0AY5ga6eDIPRCR5N6sbRMp-Gg3v7DS7-aP-iAD4dpSEtfPEI6qiDgsKoStZxsQXbsjIQ08K0io-zA_iMoYJo-g3aQBrmp861EG62MbzT_tw_9H9vkeKN33rIWj9cXUGe7ljyAC9_EiE78-jpZ3UpSBdFJjrGe5RdV_2KXz',
    altText: 'Cartera tote estructurada de cuero color caramelo con herrajes dorados',
    presetApplied: 'Blanco Puro',
    contrast: 15,
    saturation: 12,
    brightness: 6,
    isBgRemoved: true,
    selectedBackdrop: 'white',
    isLightingImproved: true,
    platformPreset: '1200 × 1600 px',
    exportFormat: 'jpg',
    exportQuality: 90,
  },
  {
    id: 'photo-4',
    filename: 'vestido_seda_verde_esmeralda.jpg',
    dimensions: '3000 × 3750 px',
    filesize: '4.5 MB',
    status: 'edited',
    badgeText: 'Editada • Blanco Puro',
    badgeType: 'emerald',
    timeAgo: 'Hace 3 h',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDLs3nsRlqGZhR09UbdkuMhbP_huWv9dMNDhq7BAZzXZ6Mc4TFi_aSpOnS2NJtzD6_yysmytqk76QZpiOja5sAIEEqCzX9qEGEF5gf72chefQDTz6rEMha8sAqGoY4FuaMuF_eSuD3PL1G_Zj4zfjTicGdq3fNwp8jVNSO_6-ck_TnkvnivmW-ihYepyH_eQjGhlHPR6HnEcetBfCSmag7QjaeA65ZgWGyHplYJiDvVYAd357n1Ss78',
    rawImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDLs3nsRlqGZhR09UbdkuMhbP_huWv9dMNDhq7BAZzXZ6Mc4TFi_aSpOnS2NJtzD6_yysmytqk76QZpiOja5sAIEEqCzX9qEGEF5gf72chefQDTz6rEMha8sAqGoY4FuaMuF_eSuD3PL1G_Zj4zfjTicGdq3fNwp8jVNSO_6-ck_TnkvnivmW-ihYepyH_eQjGhlHPR6HnEcetBfCSmag7QjaeA65ZgWGyHplYJiDvVYAd357n1Ss78',
    isolatedImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDLs3nsRlqGZhR09UbdkuMhbP_huWv9dMNDhq7BAZzXZ6Mc4TFi_aSpOnS2NJtzD6_yysmytqk76QZpiOja5sAIEEqCzX9qEGEF5gf72chefQDTz6rEMha8sAqGoY4FuaMuF_eSuD3PL1G_Zj4zfjTicGdq3fNwp8jVNSO_6-ck_TnkvnivmW-ihYepyH_eQjGhlHPR6HnEcetBfCSmag7QjaeA65ZgWGyHplYJiDvVYAd357n1Ss78',
    altText: 'Vestido lencero de satén de seda verde esmeralda profundo sobre fondo blanco impecable',
    presetApplied: 'Blanco Puro',
    contrast: 18,
    saturation: 10,
    brightness: 5,
    isBgRemoved: true,
    selectedBackdrop: 'white',
    isLightingImproved: true,
    platformPreset: '1200 × 1600 px',
    exportFormat: 'jpg',
    exportQuality: 100,
  },
  {
    id: 'photo-5',
    filename: 'anteojos_sol_diseno.jpg',
    dimensions: '2400 × 3000 px',
    filesize: '2.8 MB',
    status: 'raw',
    badgeText: 'Original sin editar',
    badgeType: 'neutral',
    timeAgo: 'Ayer',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7Mf-3tS0gq1cjWn6HxN8kel1R0FcWjEonUX5RJmrc8MSeU-b_j0q3lh8dRg148-WqeI37bvuQHisDzYj6WxxUCg4kQn3jie53xJHonEVAE6eKG6FETpNB8KB8IKm2UQSz1dB5XvOZEnE0svI3Qcl2I7SS31gZV8-3GTlSLDRK8B-wNZquYlkTr0LUFpEJqqD8hJ8TPQeNoUNaomJDKTTEWeQ5unJzjLPaCsrOvmMOGk-GCvKJHGGS',
    rawImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7Mf-3tS0gq1cjWn6HxN8kel1R0FcWjEonUX5RJmrc8MSeU-b_j0q3lh8dRg148-WqeI37bvuQHisDzYj6WxxUCg4kQn3jie53xJHonEVAE6eKG6FETpNB8KB8IKm2UQSz1dB5XvOZEnE0svI3Qcl2I7SS31gZV8-3GTlSLDRK8B-wNZquYlkTr0LUFpEJqqD8hJ8TPQeNoUNaomJDKTTEWeQ5unJzjLPaCsrOvmMOGk-GCvKJHGGS',
    isolatedImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7Mf-3tS0gq1cjWn6HxN8kel1R0FcWjEonUX5RJmrc8MSeU-b_j0q3lh8dRg148-WqeI37bvuQHisDzYj6WxxUCg4kQn3jie53xJHonEVAE6eKG6FETpNB8KB8IKm2UQSz1dB5XvOZEnE0svI3Qcl2I7SS31gZV8-3GTlSLDRK8B-wNZquYlkTr0LUFpEJqqD8hJ8TPQeNoUNaomJDKTTEWeQ5unJzjLPaCsrOvmMOGk-GCvKJHGGS',
    altText: 'Foto plana sin retoque de anteojos de sol de diseño en tono carey',
    presetApplied: 'Natural Original',
    contrast: 0,
    saturation: 0,
    brightness: 0,
    isBgRemoved: false,
    selectedBackdrop: 'neutral',
    isLightingImproved: false,
    platformPreset: '1200 × 1600 px',
    exportFormat: 'jpg',
    exportQuality: 85,
  },
  {
    id: 'photo-6',
    filename: 'sweater_cashmere_crudo.jpg',
    dimensions: '2900 × 3625 px',
    filesize: '3.9 MB',
    status: 'exported',
    badgeText: 'Exportada',
    badgeType: 'emerald',
    timeAgo: 'Hace 2 días',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFnk5s5ssTi1Gw9WNV1PeiLkF5gmH9oKwMFhwxBLT2X4rYxlyFEJ5PC4g4tRYNrbeIqCeH6ClXtitnwDTuttzObqMQZzpr4Bl7f63RJaqjerIziZa78aXXiRkOsvvWrhugMM2yAhzUCSk6Qw-LgkFinIEnIfbDiKEn5ylluakS-Wa9Lg-A-gaX2nJjlgGn7JbImNgeXmOG-p6dq4Mah6piSOtW-z7afgjOHSWmKblvwSDCPheFbvWs',
    rawImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFnk5s5ssTi1Gw9WNV1PeiLkF5gmH9oKwMFhwxBLT2X4rYxlyFEJ5PC4g4tRYNrbeIqCeH6ClXtitnwDTuttzObqMQZzpr4Bl7f63RJaqjerIziZa78aXXiRkOsvvWrhugMM2yAhzUCSk6Qw-LgkFinIEnIfbDiKEn5ylluakS-Wa9Lg-A-gaX2nJjlgGn7JbImNgeXmOG-p6dq4Mah6piSOtW-z7afgjOHSWmKblvwSDCPheFbvWs',
    isolatedImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFnk5s5ssTi1Gw9WNV1PeiLkF5gmH9oKwMFhwxBLT2X4rYxlyFEJ5PC4g4tRYNrbeIqCeH6ClXtitnwDTuttzObqMQZzpr4Bl7f63RJaqjerIziZa78aXXiRkOsvvWrhugMM2yAhzUCSk6Qw-LgkFinIEnIfbDiKEn5ylluakS-Wa9Lg-A-gaX2nJjlgGn7JbImNgeXmOG-p6dq4Mah6piSOtW-z7afgjOHSWmKblvwSDCPheFbvWs',
    altText: 'Sweater tejido trenzado de cashmere doblado sobre base de piedra suave',
    presetApplied: 'Cálido Lifestyle',
    contrast: 12,
    saturation: 15,
    brightness: 4,
    isBgRemoved: false,
    selectedBackdrop: 'beige',
    isLightingImproved: true,
    platformPreset: '1200 × 1600 px',
    exportFormat: 'jpg',
    exportQuality: 100,
  },
];
